services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: simpledb
    user: '0:0'
    ports:
      - 2500:1433
    environment:
      - SA_PASSWORD=YourStrongPwd1
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    volumes:
      - sqldata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "if [ -f /opt/mssql-tools18/bin/sqlcmd ]; then /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P YourStrongPwd1 -Q 'SELECT 1' -C; elif [ -f /opt/mssql-tools/bin/sqlcmd ]; then /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P YourStrongPwd1 -Q 'SELECT 1'; else exit 1; fi"]
      interval: 10s         # Intervalo entre cada intento de healthcheck
      timeout: 10s          # Tiempo máximo para la respuesta de la BD
      retries: 3            # Número de intentos antes de marcarlo como no saludable
      start_period: 30s     # Tiempo antes de comenzar a chequear la salud
    restart: unless-stopped

  app:
    build:
      dockerfile: "src/MySimpleLayeredApi.Api/Dockerfile"
    container_name: simpleapi
    environment:
      - ASPNETCORE_KESTREL__ENDPOINTS__HTTP__URL=http://+:80
      - ASPNETCORE_ENVIRONMENT=Docker      
    volumes:
      - appdata:/app
    ports:
      - 8080:80
    depends_on:
      db:
        condition: service_healthy  # Espera hasta que el servicio de la base de datos esté saludable
    restart: unless-stopped

volumes:
  appdata:
    driver: local
  sqldata:
    driver: local
    